In [2]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df_cust = pd.read_csv('/content/drive/MyDrive/Emergence/customers.csv')
print(df_cust.head())

  customer_id signup_date     segment country  is_enterprise
0       C0001  2023-01-04  Enterprise      IN           True
1       C0002  2023-01-14         SMB      CA          False
2       C0003  2023-01-04         SMB      IN          False
3       C0004  2023-03-19         SMB      CA          False
4       C0005  2023-03-25         NaN      IN          False

In [5]:
df_event = pd.read_csv('/content/drive/MyDrive/Emergence/events.csv')
print(df_event.head(5))

  event_id customer_id   event_type  event_date    source
0  E000001       C0001       signup  2023-03-10   organic
1  E000002       C0001       signup  2023-03-10   organic
2  E000003       C0002       signup  2023-03-27       ads
3  E000004       C0002  trial_start  2023-03-28       ads
4  E000005       C0003       signup  2023-02-19  referral

In [6]:
df_sub = pd.read_csv('/content/drive/MyDrive/Emergence/subscriptions.csv')
print(df_sub.head(5))

  subscription_id customer_id  start_date    end_date  monthly_price    status
0          S00001       C0001  2023-01-10         NaN            499    active
1          S00002       C0002  2023-01-12         NaN             49    active
2          S00003       C0003  2023-01-08  2023-02-14            149  canceled
3          S00004       C0004  2023-01-21         NaN            149    active
4          S00005       C0005  2023-04-03         NaN             99    active

# **Data Exploration**

In [7]:
df_cust.describe()

       customer_id signup_date segment country is_enterprise
count         1000         964     757    1000          1000
unique        1000          91       3       6             2
top          C1000  2023-03-25     SMB      UK         False
freq             1          17     261     177           750

In [8]:
df_cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    1000 non-null   object
 1   signup_date    964 non-null    object
 2   segment        757 non-null    object
 3   country        1000 non-null   object
 4   is_enterprise  1000 non-null   bool
dtypes: bool(1), object(4)
memory usage: 32.4+ KB

In [9]:
df_event.describe()

       event_id customer_id event_type  event_date    source
count      2411        2411       2411        2411      2411
unique     2411        1000          4         175         4
top     E002411       C0846     signup  2023-01-19  outbound
freq          1           5       1094          40       643

In [10]:
df_event.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2411 entries, 0 to 2410
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event_id     2411 non-null   object
 1   customer_id  2411 non-null   object
 2   event_type   2411 non-null   object
 3   event_date   2411 non-null   object
 4   source       2411 non-null   object
dtypes: object(5)
memory usage: 94.3+ KB

In [11]:
df_sub.describe()

       monthly_price
count     941.000000
mean      254.356004
std       223.390712
min        49.000000
25%        79.000000
50%       149.000000
75%       499.000000
max       699.000000

In [12]:
df_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941 entries, 0 to 940
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   subscription_id  941 non-null    object
 1   customer_id      941 non-null    object
 2   start_date       941 non-null    object
 3   end_date         223 non-null    object
 4   monthly_price    941 non-null    int64
 5   status           941 non-null    object
dtypes: int64(1), object(5)
memory usage: 44.2+ KB

In [13]:
# Check data types of all fields in customer table
df_cust.dtypes

customer_id      object
signup_date      object
segment          object
country          object
is_enterprise      bool
dtype: object

In [14]:
# Update data type of 'signup_date' from object to datetime
df_cust['signup_date'] = pd.to_datetime(df_cust['signup_date'])
df_cust.dtypes

customer_id              object
signup_date      datetime64[ns]
segment                  object
country                  object
is_enterprise              bool
dtype: object

In [15]:
# Check data types of all fields in events table
df_event.dtypes

event_id       object
customer_id    object
event_type     object
event_date     object
source         object
dtype: object

In [16]:
# Update data type of 'event_date' from object to datetime
df_event['event_date'] = pd.to_datetime(df_event['event_date'])
df_event.dtypes

event_id               object
customer_id            object
event_type             object
event_date     datetime64[ns]
source                 object
dtype: object

In [17]:
# Check data types of all fields in subscription table
df_sub.dtypes

subscription_id    object
customer_id        object
start_date         object
end_date           object
monthly_price       int64
status             object
dtype: object

In [18]:
# Update data type of 'start_date' and 'end_date' from object to datetime
df_sub['start_date'] = pd.to_datetime(df_sub['start_date'])
df_sub['end_date'] = pd.to_datetime(df_sub['end_date'])
df_sub.dtypes

subscription_id            object
customer_id                object
start_date         datetime64[ns]
end_date           datetime64[ns]
monthly_price               int64
status                     object
dtype: object

In [19]:
df_cust['segment'].unique()

array(['Enterprise', 'SMB', nan, 'Mid-Market'], dtype=object)

In [20]:
df_cust['country'].unique()

array(['IN', 'CA', 'US', 'AU', 'DE', 'UK'], dtype=object)

In [21]:
df_event['event_type'].unique()

array(['signup', 'trial_start', 'churned', 'activated'], dtype=object)

In [22]:
df_event['source'].unique()

array(['organic', 'ads', 'referral', 'outbound'], dtype=object)

In [23]:
df_sub['monthly_price'].unique()

array([499,  49, 149,  99, 299,  79, 699])

In [24]:
df_sub['status'].unique()

array(['active', 'canceled'], dtype=object)

# **Check for Duplicates**

In [25]:
# Count how many rows (excluding the first occurrence) are duplicates in events table
count_of_duplicates = df_event.duplicated(subset=['customer_id', 'event_type', 'event_date', 'source'])
print(count_of_duplicates.sum())

94

In [26]:
# Remove duplicates keeping only the first occurance
df_event_no_duplicates = df_event.drop_duplicates(subset=['customer_id', 'event_type', 'event_date', 'source'], keep='first')

In [27]:
# Reset index after removing duplicate rows
df_event_no_duplicates.reset_index(drop=True, inplace=True)
df_event_no_duplicates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2317 entries, 0 to 2316
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event_id     2317 non-null   object
 1   customer_id  2317 non-null   object
 2   event_type   2317 non-null   object
 3   event_date   2317 non-null   datetime64[ns]
 4   source       2317 non-null   object
dtypes: datetime64[ns](1), object(4)
memory usage: 90.6+ KB

In [28]:
# Check for duplicates in subscription table
count_of_duplicates2 = df_sub.duplicated(subset=['customer_id', 'start_date', 'end_date', 'monthly_price', 'status'])
print(count_of_duplicates2.sum())

35

In [29]:
# Remove duplicate rows keeping only the first occurance
df_sub_no_duplicates = df_sub.drop_duplicates(subset=['customer_id', 'start_date', 'end_date', 'monthly_price', 'status'], keep='first')

In [30]:
# Reset index after removing duplicate rows
df_sub_no_duplicates.reset_index(drop=True, inplace=True)
df_sub_no_duplicates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 906 entries, 0 to 905
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   subscription_id  906 non-null    object
 1   customer_id      906 non-null    object
 2   start_date       906 non-null    datetime64[ns]
 3   end_date         223 non-null    datetime64[ns]
 4   monthly_price    906 non-null    int64
 5   status           906 non-null    object
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 42.6+ KB

# **Handle missing values in customer table**

In [31]:
# Fill missing 'segment' data with 'Unknown'
df_cust['segment'].fillna('Unknown', inplace=True)
df_cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    1000 non-null   object
 1   signup_date    964 non-null    datetime64[ns]
 2   segment        1000 non-null   object
 3   country        1000 non-null   object
 4   is_enterprise  1000 non-null   bool
dtypes: bool(1), datetime64[ns](1), object(3)
memory usage: 32.4+ KB

/tmp/ipython-input-2162548728.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cust['segment'].fillna('Unknown', inplace=True)

In [32]:
# Drop rows where signup date is missing
df_cust.dropna(subset=['signup_date'], inplace=True)
df_cust.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    964 non-null    object
 1   signup_date    964 non-null    datetime64[ns]
 2   segment        964 non-null    object
 3   country        964 non-null    object
 4   is_enterprise  964 non-null    bool
dtypes: bool(1), datetime64[ns](1), object(3)
memory usage: 38.6+ KB

In [33]:
# Reset index
df_cust.reset_index(drop=True, inplace=True)
df_cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    964 non-null    object
 1   signup_date    964 non-null    datetime64[ns]
 2   segment        964 non-null    object
 3   country        964 non-null    object
 4   is_enterprise  964 non-null    bool
dtypes: bool(1), datetime64[ns](1), object(3)
memory usage: 31.2+ KB

# **Check for inconsistencies in data**

In [34]:
# Filter for cancelled status AND inconsistent times
inconsistent_cancelled = df_sub_no_duplicates[
    (df_sub_no_duplicates['status'] == 'canceled') &
    (df_sub_no_duplicates['end_date'] < df_sub_no_duplicates['start_date'])]
print(inconsistent_cancelled)

Empty DataFrame
Columns: [subscription_id, customer_id, start_date, end_date, monthly_price, status]
Index: []

# **Write the cleaned data into new csv files**

In [35]:
df_cust.to_csv('/content/drive/MyDrive/Emergence/customers_final.csv', index=False)

In [36]:
df_event_no_duplicates.to_csv('/content/drive/MyDrive/Emergence/events_final.csv', index=False)

In [37]:
df_sub_no_duplicates.to_csv('/content/drive/MyDrive/Emergence/subscriptions_final.csv', index=False)